import { ProjectsSectionType } from "../types/section";
import { getId } from "../utils/helper";

export const projectsSection: ProjectsSectionType = {
  title: "my projects",
  projects: [
    {
      id: getId(),
      name: "Chat App",
      url: "https://github.com/IshimweJoliePrincesse/Real-Time-Chatapp",
      repo: "https://github.com/IshimweJoliePrincesse/Real-Time-Chatapp",
      img: "https://blog.chatengine.io/assets/fastapi-react.png",
      year: 2023,
      tags: ["React", "TailwindCSS"],
    },
    {
      id: getId(),
      name: "Online Library Management System",
      url: "https://github.com/IshimweJoliePrincesse/LMS",
      repo: "https://github.com/IshimweJoliePrincesse/LMS",
      img: "https://media.licdn.com/dms/image/D5612AQHH0VLhvqde8g/article-cover_image-shrink_600_2000/0/1693156805497?e=2147483647&v=beta&t=9bPAL9yB4QO84Yz_-dTwuYNaBlcB6gyUFU0Gyy7x7Dw",
      year: 2024,
      tags: ["PHP, MYSQL, Bootstrap"],
    },
    {
      id: getId(),
      name: "Site Blocker",
      url: "https://github.com/IshimweJoliePrincesse/site_blocker",
      repo: "https://github.com/IshimweJoliePrincesse/site_blocker",
      img: "https://lh3.googleusercontent.com/Eso3lu9PdHlvxZ4PjrTSVbyCIiWRbU_IUM0pZVAkDzFRiYBtPtiJ53GD7BWBupn1Znudr0FD9OQyXthjqKBAVaENUw=s1280-w1280-h800",
      year: 2024,
      tags: ["HTML, CSS, Javascript"],
    },
    {
      id: getId(),
      name: "Fashion Website",
      url: "https://github.com/IshimweJoliePrincesse/Frontend_with-Tailwindcss",
      repo: "https://github.com/IshimweJoliePrincesse/Frontend_with-Tailwindcss",
      img: "https://images-platform.99static.com//sAPew3Y37yZPrF5YlVq52WrmINw=/152x0:1445x1293/fit-in/500x500/99designs-contests-attachments/41/41113/attachment_41113601",
      year: 2024,
      tags: ["HTML, TailwindCSS, Javascript"],
    },
    {
      id: getId(),
      name: "Movie Ticket Booking",
      url: "https://github.com/IshimweJoliePrincesse/MovieTicketBooking",
      repo: "https://github.com/IshimweJoliePrincesse/MovieTicketBooking",
      img: "https://projectsforeveryone.com/wp-content/uploads/2021/03/ticket-system-e1637130674304.webp",
      year: 2024,
      tags: ["JAVA"],
    },
    {
      id: getId(),
      name: "Spotify_clone",
      url: "https://github.com/IshimweJoliePrincesse/spotify_clone",
      repo: "https://github.com/IshimweJoliePrincesse/spotify_clone",
      img: "https://s3-alpha.figma.com/hub/file/2763489152/a4349c9e-c21d-4e2f-9902-7bac37760863-cover.png",
      year: 2024,
      tags: ["TailwindCSS, ReactJs"],
    },
    {
      id: getId(),
      name: "Food Delivery App",
      url: "https://github.com/IshimweJoliePrincesse/Food_delivery-app",
      repo: "https://github.com/IshimweJoliePrincesse/Food_delivery-app",
      img: "https://repository-images.githubusercontent.com/774882122/0022ed18-eedf-4833-a0ec-58e5a4a62c6f",
      year: 2024,
      tags: ["PHP, MYSQL, Bootstrap"],
    },
    {
      id: getId(),
      name: "My first portfolio",
      url: "https://jolieprincesseportfolio.vercel.app/",
      repo: "https://github.com/IshimweJoliePrincesse/portfolio",
      img: "https://ibb.co/hmsY5WP",
      year: 2023,
      tags: ["HTML, CSS, JAVASCRIPT"],
    },
    {
      id: getId(),
      name: "Smart Cities",
      url: "https://github.com/IshimweJoliePrincesse/smartcities",
      repo: "https://github.com/IshimweJoliePrincesse/smartcities",
      img: "https://www.bpcbt.com/hubfs/2021_campaigns/smart%20city%20survey/blog/SCS_blogpost4.jpg",
      year: 2024,
      tags: ["PHP, MYSQL, HTML, CSS"],
    },
    {
      id: getId(),
      name: "Online Library Management System",
      url: "https://github.com/IshimweJoliePrincesse/LMS",
      repo: "https://github.com/IshimweJoliePrincesse/LMS",
      img: "https://media.licdn.com/dms/image/D5612AQHH0VLhvqde8g/article-cover_image-shrink_600_2000/0/1693156805497?e=2147483647&v=beta&t=9bPAL9yB4QO84Yz_-dTwuYNaBlcB6gyUFU0Gyy7x7Dw",
      year: 2024,
      tags: ["PHP, MYSQL, Bootstrap"],
    },
    {
      id: getId(),
      name: "News Portal",
      url: "https://github.com/IshimweJoliePrincesse/News_portal",
      repo: "https://github.com/IshimweJoliePrincesse/News_portal",
      img: "https://cdn.dribbble.com/userupload/3254197/file/original-2f14947dad1cc56d4327e09db15ca682.png?resize=752x",
      year: 2024,
      tags: ["PHP, MYSQL, Bootstrap"],
    },
    {
      id: getId(),
      name: "healthcare dashboard",
      url: "https://github.com/IshimweJoliePrincesse/haealth_care-dashboard",
      repo: "https://github.com/IshimweJoliePrincesse/haealth_care-dashboard",
      img: "https://ibb.co/HpsCmY7",
      year: 2024,
      tags: ["ReactJS, TailwindCSS, APIs"],
    },
    {
      id: getId(),
      name: "Swagger Demo",
      url: "https://github.com/IshimweJoliePrincesse/backend_swagger_demo",
      repo: "https://github.com/IshimweJoliePrincesse/backend_swagger_demo",
      img: "https://static1.smartbear.co/swagger/media/images/tools/opensource/swagger_ui.png",
      year: 2024,
      tags: ["Javascript"],
    },
    {
      id: getId(),
      name: "Url Shortening",
      url: "https://github.com/IshimweJoliePrincesse/url_shortening",
      repo: "https://github.com/IshimweJoliePrincesse/url_shortening",
      img: "https://www.bulkgate.com/wp-content/uploads/2022/05/blog-url-shortener.jpg",
      year: 2024,
      tags: ["JWT, JOI"],
    },
    {
      id: getId(),
      name: " E_Commerce Website",
      url: "https://github.com/IshimweJoliePrincesse/e_commrce",
      repo: "https://github.com/IshimweJoliePrincesse/e_commrce",
      img: "https://blog.powr.io/hs-fs/hubfs/ecommerce-website-example-github.webp?width=801&height=450&name=ecommerce-website-example-github.webp",
      year: 2024,
      tags: ["ReactJS, Redux, Material UI"],
    },
    {
      id: getId(),
      name: "CRUD API",
      url: "https://github.com/IshimweJoliePrincesse/REACT_NODEJS",
      repo: "https://github.com/IshimweJoliePrincesse/REACT_NODEJS",
      img: "https://www.datocms-assets.com/48294/1691046464-crud-operations-1-crud-operations.png?auto=format",
      year: 2024,
      tags: ["Javascript"],
    },
  ],
};
